//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeTraversal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tree
    {
        public int Id { get; set; }
        public string Parent { get; set; }
        public string Title { get; set; }
        public int Left { get; set; }
        public int Right { get; set; }
    }
}
